repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      # запрет размещения докстрингов перед кодом
      - id: check-docstring-first
      - id: check-case-conflict
      # запрет на коммит неразрешенных конфликтов мерджа гита
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude_types: [xml]
      # запрет коммитов в мастер и в релиз
      - id: no-commit-to-branch
        args: [ --branch=master, --branch=release, --branch=main ]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'
    hooks:
      - id: autopep8
        args: ["-i", --max-line-length=100]
  - repo: https://github.com/psf/black
    rev: '23.9.1'
    hooks:
      - id: black
        args: [--line-length=100]
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ["--profile", "black", --line-length=100]
  - repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8
        args: [--max-line-length=100]
