"""about_me and last_seen fields for user

Revision ID: 785b49ae3851
Revises: 5412bbee97cf
Create Date: 2023-10-02 16:00:15.692215

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "785b49ae3851"
down_revision: Union[str, None] = "5412bbee97cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("about_me", sa.String(length=140), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("last_seen", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_seen")
    op.drop_column("users", "about_me")
    # ### end Alembic commands ###
